# Proper manylinux builds would require building in a manylinux image, then
# unpacking, moving out purelib, and repacking (using a recent version of wheel),
# then returning to the image to retag.

strategy:
  matrix:
    Linux_py36:
        vmImage: 'ubuntu-16.04'
        pythonVersion: '3.6'
    Linux_py38:
        vmImage: 'ubuntu-16.04'
        pythonVersion: '3.8'
    macOS_py36:
      vmImage: 'macOS-10.14'
      pythonVersion: '3.6'
    macOS_py38:
      vmImage: 'macOS-10.14'
      pythonVersion: '3.8'
    Windows_py36:
      vmImage: 'windows-2019'
      pythonVersion: '3.6'
    Windows_py38:
      vmImage: 'windows-2019'
      pythonVersion: '3.8'

pool:
  vmImage: '$(vmImage)'

steps:

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(pythonVersion)'
    architecture: 'x64'

- bash: |
    git submodule init &&
      git submodule update &&
      python -mpip install --upgrade pip setuptools wheel &&
      python -mpip wheel --no-deps --wheel-dir dist . &&
      python -mpip install dist/*
  displayName: 'Build & install'

- bash: |
    python -mpip install coverage &&
      cd examples &&
      python __run_all_examples__.py --cov
  displayName: 'Test'
